### ISSUE TITLE
Org owner/name missing in default deployment name

### ISSUE THREAD

**Issue by jasonkuhrt** [superfly/fly-pr-review-apps#10]
```
::set-output name=hostname::pr-1-null-null.fly.dev
[325](https://github.com/prisma/pdp-spike-fly/runs/7618582925?check_suite_focus=true#step:4:326)
```

Notice `null-null` there. Why would that be?

**Comment by jasonkuhrt** [comment]
```
+ jq -r .event.base.repo.owner /github/workflow/event.json
[14](https://github.com/prisma/pdp-spike-fly/runs/7618752093?check_suite_focus=true#step:4:15)
+ REPO_OWNER=null
[15](https://github.com/prisma/pdp-spike-fly/runs/7618752093?check_suite_focus=true#step:4:16)
+ jq -r .event.base.repo.name /github/workflow/event.json
[16](https://github.com/prisma/pdp-spike-fly/runs/7618752093?check_suite_focus=true#step:4:17)
+ REPO_NAME=null
```

**Comment by jasonkuhrt** [comment]
Maybe its the event that I'm working with:

```
on:
  - pull_request
```

**Comment by tovbinm** [comment]
I have the same issue. The org owner and repo name are not being picked up from the event json. It would be great to be able to set them manually. 
<img width="595" alt="Screen Shot 2022-11-05 at 09 50 53" src="https://user-images.githubusercontent.com/629845/200131780-1a2db322-8bf1-4462-9b22-52b9dcbf83cf.png">

**Comment by HuyAms** [comment]
I am using the same action for 2 projects. One shows the correct REPO_OWNER and REPO_NAME and the other doesn't. I was wondering why so

**Comment by tovbinm** [comment]
I fixed it here - https://github.com/superfly/fly-pr-review-apps/pull/17
