### ISSUE TITLE
Ability to set --env

### ISSUE THREAD

**Issue by HuyAms** [superfly/fly-pr-review-apps#18]
Hi, 

When deploying an app, I would love to set some env variables. 

[flyctl](https://fly.io/docs/flyctl/deploy/) has an option to set the secret

```
flyctl deploy --env strings
```
Could we add that option to the action?

Thank so much!

**Comment by HuyAms** [comment]
It seems that we do support it. Need to update the README
https://github.com/superfly/fly-pr-review-apps/blob/main/action.yml#L28

**Comment by harrygr** [comment]
I can't see any support for build env. Can you share how you achieved this?
